export const Operations = {
    CANCEL_ORDERS: "cancelOrders",
    LIST_CLEARED_ORDERS: "listClearedOrders",
    LIST_COMPETITIONS: "listCompetitions",
    LIST_COUNTRIES: "listCountries",
    LIST_CURRENT_ORDERS: "listCurrentOrders",
    LIST_EVENT_TYPES: "listEventTypes",
    LIST_EVENTS: "listEvents",
    LIST_MARKET_BOOK: "listMarketBook",
    LIST_MARKET_CATALOGUE: "listMarketCatalogue",
    LIST_MARKET_PROFIT_AND_LOSS: "listMarketProfitAndLoss",
    LIST_MARKET_TYPES: "listMarketTypes",
    LIST_RUNNER_BOOK: "listRunnerBook",
    LIST_TIME_RANGES: "listTimeRanges",
    LIST_VENUES: "listVenues",
    PLACE_ORDERS: "placeOrders",
    REPLACE_ORDERS: "replaceOrders",
    UPDATE_ORDERS: "updateOrders"
};

export const EventTypeIds = {
    SOCCER: "1",
    TENNIS: "2",
    GOLF: "3",
    CRICKET: "4",
    RUGBY_UNION: "5",
    BOXING: "6",
    HORSE_RACING: "7",
    MOTOR_SPORT: "8",
    SPECIAL_BETS: "10",
    CYCLING: "11",
    RUGBY_LEAGUE: "1477",
    DARTS: "3520",
    ATHLETICS: "3988",
    GREYHOUND_RACING: "4339",
    FINANCIAL_BETS: "6231",
    SNOOKER: "6422",
    AMERICAN_FOOTBALL: "6423",
    BASEBALL: "7511",
    BASKETBALL: "7522",
    ICE_HOCKEY: "7524",
    AUSTRALIAN_RULES: "61420",
    HANDBALL: "468328",
    WINTER_SPORTS: "451485",
    YACHTING: "998916",
    VOLLEYBALL: "998917",
    POLITICS: "2378961",
    GAELIC_GAMES: "2152880",
    MIXED_MARTIAL_ARTS: "26420387",
    ESPORTS: "27454571"
};